default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV['DB_POOL'] || 10 %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 3306 %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE'] %>
  reconnect: true

development:
  <<: *default

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV['DB_POOL'] || 10 %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || 3306 %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: 'comics_test'
  reconnect: true

staging:
  <<: *default

production:
  <<: *default
